services:
  backend:
    container_name: backend_cms
    build:
      context: ./backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    # depends_on:
    #   - db

  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - backend
  
  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./frontend
  #   command: ["npm", "run", "dev", "--", "--host"]
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   depends_on:
  #     - backend

  # db:
  #   image: postgres
  #   container_name: db
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: mypassword
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: test@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - "8080:80"

# volumes:
#   db_data:
